//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.Editor.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supported files.
        /// </summary>
        internal static string FilterExtract {
            get {
                return ResourceManager.GetString("FilterExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insertable files.
        /// </summary>
        internal static string FilterInsertable {
            get {
                return ResourceManager.GetString("FilterInsertable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDF files.
        /// </summary>
        internal static string FilterPdf {
            get {
                return ResourceManager.GetString("FilterPdf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MenuAdd {
            get {
                return ResourceManager.GetString("MenuAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow using contents for accessibility.
        /// </summary>
        internal static string MenuAllowAccessibility {
            get {
                return ResourceManager.GetString("MenuAllowAccessibility", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow creating and editing annotations.
        /// </summary>
        internal static string MenuAllowAnnotation {
            get {
                return ResourceManager.GetString("MenuAllowAnnotation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow inserting and removing pages.
        /// </summary>
        internal static string MenuAllowAssemble {
            get {
                return ResourceManager.GetString("MenuAllowAssemble", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow copying text and images.
        /// </summary>
        internal static string MenuAllowCopy {
            get {
                return ResourceManager.GetString("MenuAllowCopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow extracting pages.
        /// </summary>
        internal static string MenuAllowExtract {
            get {
                return ResourceManager.GetString("MenuAllowExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow filling in form fields.
        /// </summary>
        internal static string MenuAllowForm {
            get {
                return ResourceManager.GetString("MenuAllowForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow printing.
        /// </summary>
        internal static string MenuAllowPrint {
            get {
                return ResourceManager.GetString("MenuAllowPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string MenuAuthor {
            get {
                return ResourceManager.GetString("MenuAuthor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string MenuBackup {
            get {
                return ResourceManager.GetString("MenuBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete old backup files automatically.
        /// </summary>
        internal static string MenuBackupAutoDelete {
            get {
                return ResourceManager.GetString("MenuBackupAutoDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable backup.
        /// </summary>
        internal static string MenuBackupEnabled {
            get {
                return ResourceManager.GetString("MenuBackupEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MenuCancel {
            get {
                return ResourceManager.GetString("MenuCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        internal static string MenuCheckUpdate {
            get {
                return ResourceManager.GetString("MenuCheckUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string MenuClear {
            get {
                return ResourceManager.GetString("MenuClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MenuConfirmPassword {
            get {
                return ResourceManager.GetString("MenuConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string MenuCreationTime {
            get {
                return ResourceManager.GetString("MenuCreationTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string MenuCreator {
            get {
                return ResourceManager.GetString("MenuCreator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save path.
        /// </summary>
        internal static string MenuDestination {
            get {
                return ResourceManager.GetString("MenuDestination", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string MenuDetails {
            get {
                return ResourceManager.GetString("MenuDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string MenuDown {
            get {
                return ResourceManager.GetString("MenuDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dpi.
        /// </summary>
        internal static string MenuDpi {
            get {
                return ResourceManager.GetString("MenuDpi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string MenuEncryption {
            get {
                return ResourceManager.GetString("MenuEncryption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encrypt the PDF with password.
        /// </summary>
        internal static string MenuEncryptionEnabled {
            get {
                return ResourceManager.GetString("MenuEncryptionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string MenuEncryptionMethod {
            get {
                return ResourceManager.GetString("MenuEncryptionMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string MenuExtract {
            get {
                return ResourceManager.GetString("MenuExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All pages.
        /// </summary>
        internal static string MenuExtractAll {
            get {
                return ResourceManager.GetString("MenuExtractAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extract with other settings.
        /// </summary>
        internal static string MenuExtractOthers {
            get {
                return ResourceManager.GetString("MenuExtractOthers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specified range.
        /// </summary>
        internal static string MenuExtractRange {
            get {
                return ResourceManager.GetString("MenuExtractRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected pages.
        /// </summary>
        internal static string MenuExtractSelected {
            get {
                return ResourceManager.GetString("MenuExtractSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string MenuFilename {
            get {
                return ResourceManager.GetString("MenuFilename", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filesize.
        /// </summary>
        internal static string MenuFilesize {
            get {
                return ResourceManager.GetString("MenuFilesize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MenuFiletype {
            get {
                return ResourceManager.GetString("MenuFiletype", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string MenuFormat {
            get {
                return ResourceManager.GetString("MenuFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frame only.
        /// </summary>
        internal static string MenuFrameOnly {
            get {
                return ResourceManager.GetString("MenuFrameOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string MenuInsert {
            get {
                return ResourceManager.GetString("MenuInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert at the end.
        /// </summary>
        internal static string MenuInsertBack {
            get {
                return ResourceManager.GetString("MenuInsertBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert at the beginning.
        /// </summary>
        internal static string MenuInsertFront {
            get {
                return ResourceManager.GetString("MenuInsertFront", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert at other position.
        /// </summary>
        internal static string MenuInsertOthers {
            get {
                return ResourceManager.GetString("MenuInsertOthers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert position.
        /// </summary>
        internal static string MenuInsertPosition {
            get {
                return ResourceManager.GetString("MenuInsertPosition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep bookmarks of the source PDF file.
        /// </summary>
        internal static string MenuKeepOutlines {
            get {
                return ResourceManager.GetString("MenuKeepOutlines", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string MenuKeywords {
            get {
                return ResourceManager.GetString("MenuKeywords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        internal static string MenuLastWriteTime {
            get {
                return ResourceManager.GetString("MenuLastWriteTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string MenuLayout {
            get {
                return ResourceManager.GetString("MenuLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string MenuMetadata {
            get {
                return ResourceManager.GetString("MenuMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forth.
        /// </summary>
        internal static string MenuMoveNext {
            get {
                return ResourceManager.GetString("MenuMoveNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MenuMovePrevious {
            get {
                return ResourceManager.GetString("MenuMovePrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MenuOk {
            get {
                return ResourceManager.GetString("MenuOk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open with password.
        /// </summary>
        internal static string MenuOpenWithPassword {
            get {
                return ResourceManager.GetString("MenuOpenWithPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string MenuOperations {
            get {
                return ResourceManager.GetString("MenuOperations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string MenuOthers {
            get {
                return ResourceManager.GetString("MenuOthers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string MenuOwnerPassword {
            get {
                return ResourceManager.GetString("MenuOwnerPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page count.
        /// </summary>
        internal static string MenuPageCount {
            get {
                return ResourceManager.GetString("MenuPageCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDF version.
        /// </summary>
        internal static string MenuPdfVersion {
            get {
                return ResourceManager.GetString("MenuPdfVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beginning.
        /// </summary>
        internal static string MenuPositionFirst {
            get {
                return ResourceManager.GetString("MenuPositionFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string MenuPositionLast {
            get {
                return ResourceManager.GetString("MenuPositionLast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected position.
        /// </summary>
        internal static string MenuPositionSelected {
            get {
                return ResourceManager.GetString("MenuPositionSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Behind the number of.
        /// </summary>
        internal static string MenuPositionSpecified {
            get {
                return ResourceManager.GetString("MenuPositionSpecified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string MenuPreview {
            get {
                return ResourceManager.GetString("MenuPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        internal static string MenuProducer {
            get {
                return ResourceManager.GetString("MenuProducer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        internal static string MenuRecent {
            get {
                return ResourceManager.GetString("MenuRecent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show recently used files.
        /// </summary>
        internal static string MenuRecentVisible {
            get {
                return ResourceManager.GetString("MenuRecentVisible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MenuRedraw {
            get {
                return ResourceManager.GetString("MenuRedraw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove other pages.
        /// </summary>
        internal static string MenuRemoveOthers {
            get {
                return ResourceManager.GetString("MenuRemoveOthers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string MenuRotateLeft {
            get {
                return ResourceManager.GetString("MenuRotateLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string MenuRotateRight {
            get {
                return ResourceManager.GetString("MenuRotateRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save options.
        /// </summary>
        internal static string MenuSaveOptions {
            get {
                return ResourceManager.GetString("MenuSaveOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string MenuSelect {
            get {
                return ResourceManager.GetString("MenuSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        internal static string MenuSelectClear {
            get {
                return ResourceManager.GetString("MenuSelectClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invert selection.
        /// </summary>
        internal static string MenuSelectFlip {
            get {
                return ResourceManager.GetString("MenuSelectFlip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSetting {
            get {
                return ResourceManager.GetString("MenuSetting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use owner password.
        /// </summary>
        internal static string MenuSharePassword {
            get {
                return ResourceManager.GetString("MenuSharePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reduce duplicated resources.
        /// </summary>
        internal static string MenuShrinkResources {
            get {
                return ResourceManager.GetString("MenuShrinkResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save as a separate file per page.
        /// </summary>
        internal static string MenuSplit {
            get {
                return ResourceManager.GetString("MenuSplit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string MenuSubject {
            get {
                return ResourceManager.GetString("MenuSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string MenuSummary {
            get {
                return ResourceManager.GetString("MenuSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target pages.
        /// </summary>
        internal static string MenuTarget {
            get {
                return ResourceManager.GetString("MenuTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        internal static string MenuTemp {
            get {
                return ResourceManager.GetString("MenuTemp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string MenuUp {
            get {
                return ResourceManager.GetString("MenuUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string MenuUserPassword {
            get {
                return ResourceManager.GetString("MenuUserPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string MenuVersion {
            get {
                return ResourceManager.GetString("MenuVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One column.
        /// </summary>
        internal static string MenuViewOneColumn {
            get {
                return ResourceManager.GetString("MenuViewOneColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single page.
        /// </summary>
        internal static string MenuViewSinglePage {
            get {
                return ResourceManager.GetString("MenuViewSinglePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two column (left).
        /// </summary>
        internal static string MenuViewTwoColumnLeft {
            get {
                return ResourceManager.GetString("MenuViewTwoColumnLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two column (right).
        /// </summary>
        internal static string MenuViewTwoColumnRight {
            get {
                return ResourceManager.GetString("MenuViewTwoColumnRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two page (left).
        /// </summary>
        internal static string MenuViewTwoPageLeft {
            get {
                return ResourceManager.GetString("MenuViewTwoPageLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two page (right).
        /// </summary>
        internal static string MenuViewTwoPageRight {
            get {
                return ResourceManager.GetString("MenuViewTwoPageRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ZoomIn.
        /// </summary>
        internal static string MenuZoomIn {
            get {
                return ResourceManager.GetString("MenuZoomIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ZoomOut.
        /// </summary>
        internal static string MenuZoomOut {
            get {
                return ResourceManager.GetString("MenuZoomOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup process failed..
        /// </summary>
        internal static string MessageBackupError {
            get {
                return ResourceManager.GetString("MessageBackupError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading {0} ....
        /// </summary>
        internal static string MessageLoading {
            get {
                return ResourceManager.GetString("MessageLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to get PDF metadata..
        /// </summary>
        internal static string MessageMetadataError {
            get {
                return ResourceManager.GetString("MessageMetadataError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File is not in PDF format or corrupted..
        /// </summary>
        internal static string MessageOpenError {
            get {
                return ResourceManager.GetString("MessageOpenError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDF is modified. Do you want to overwrite?.
        /// </summary>
        internal static string MessageOverwrite {
            get {
                return ResourceManager.GetString("MessageOverwrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} pages.
        /// </summary>
        internal static string MessagePage {
            get {
                return ResourceManager.GetString("MessagePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter the owner password for opening and editing {0}..
        /// </summary>
        internal static string MessagePassword {
            get {
                return ResourceManager.GetString("MessagePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the removal range..
        /// </summary>
        internal static string MessageRangeError {
            get {
                return ResourceManager.GetString("MessageRangeError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 1,2,4-7,9.
        /// </summary>
        internal static string MessageRangeExample {
            get {
                return ResourceManager.GetString("MessageRangeExample", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved as {0}.
        /// </summary>
        internal static string MessageSaved {
            get {
                return ResourceManager.GetString("MessageSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saving as {0} ....
        /// </summary>
        internal static string MessageSaving {
            get {
                return ResourceManager.GetString("MessageSaving", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} pages selected.
        /// </summary>
        internal static string MessageSelection {
            get {
                return ResourceManager.GetString("MessageSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} pages.
        /// </summary>
        internal static string MessageTotalPage {
            get {
                return ResourceManager.GetString("MessageTotalPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a backup folder..
        /// </summary>
        internal static string TitleBackup {
            get {
                return ResourceManager.GetString("TitleBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string TitleEncryption {
            get {
                return ResourceManager.GetString("TitleEncryption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extraction details.
        /// </summary>
        internal static string TitleExtract {
            get {
                return ResourceManager.GetString("TitleExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insertion details.
        /// </summary>
        internal static string TitleInsert {
            get {
                return ResourceManager.GetString("TitleInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDF Metadata.
        /// </summary>
        internal static string TitleMetadata {
            get {
                return ResourceManager.GetString("TitleMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string TitleOpen {
            get {
                return ResourceManager.GetString("TitleOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input password.
        /// </summary>
        internal static string TitlePassword {
            get {
                return ResourceManager.GetString("TitlePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}/{2} page).
        /// </summary>
        internal static string TitlePreview {
            get {
                return ResourceManager.GetString("TitlePreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removal details.
        /// </summary>
        internal static string TitleRemove {
            get {
                return ResourceManager.GetString("TitleRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string TitleSaveAs {
            get {
                return ResourceManager.GetString("TitleSaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CubePDF Utility settings.
        /// </summary>
        internal static string TitleSetting {
            get {
                return ResourceManager.GetString("TitleSetting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a temp folder. If you do not specify a temp folder, the same folder as the source file will be used..
        /// </summary>
        internal static string TitleTemp {
            get {
                return ResourceManager.GetString("TitleTemp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extract the selected pages.
        /// </summary>
        internal static string TooltipExtract {
            get {
                return ResourceManager.GetString("TooltipExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert behind selected position.
        /// </summary>
        internal static string TooltipInsert {
            get {
                return ResourceManager.GetString("TooltipInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDF document metadata.
        /// </summary>
        internal static string TooltipMetadata {
            get {
                return ResourceManager.GetString("TooltipMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove the selected pages.
        /// </summary>
        internal static string TooltipRemove {
            get {
                return ResourceManager.GetString("TooltipRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TooltipSave {
            get {
                return ResourceManager.GetString("TooltipSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string UnitByte {
            get {
                return ResourceManager.GetString("UnitByte", resourceCulture);
            }
        }
    }
}
