//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.Editor.Properties {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Supported files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterExtract {
            get {
                return ResourceManager.GetString("FilterExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Insertable files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterInsertable {
            get {
                return ResourceManager.GetString("FilterInsertable", resourceCulture);
            }
        }

        /// <summary>
        ///   PDF files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPdf {
            get {
                return ResourceManager.GetString("FilterPdf", resourceCulture);
            }
        }

        /// <summary>
        ///   Add ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAdd {
            get {
                return ResourceManager.GetString("MenuAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Allow using contents for accessibility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAllowAccessibility {
            get {
                return ResourceManager.GetString("MenuAllowAccessibility", resourceCulture);
            }
        }

        /// <summary>
        ///   Allow creating and editing annotations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAllowAnnotation {
            get {
                return ResourceManager.GetString("MenuAllowAnnotation", resourceCulture);
            }
        }

        /// <summary>
        ///   Allow inserting and removing pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAllowAssemble {
            get {
                return ResourceManager.GetString("MenuAllowAssemble", resourceCulture);
            }
        }

        /// <summary>
        ///   Allow copying text and images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAllowCopy {
            get {
                return ResourceManager.GetString("MenuAllowCopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Allow extracting pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAllowExtract {
            get {
                return ResourceManager.GetString("MenuAllowExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Allow filling in form fields に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAllowForm {
            get {
                return ResourceManager.GetString("MenuAllowForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Allow printing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAllowPrint {
            get {
                return ResourceManager.GetString("MenuAllowPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAuthor {
            get {
                return ResourceManager.GetString("MenuAuthor", resourceCulture);
            }
        }

        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCancel {
            get {
                return ResourceManager.GetString("MenuCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuClear {
            get {
                return ResourceManager.GetString("MenuClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuConfirmPassword {
            get {
                return ResourceManager.GetString("MenuConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Creation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCreationTime {
            get {
                return ResourceManager.GetString("MenuCreationTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Creator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCreator {
            get {
                return ResourceManager.GetString("MenuCreator", resourceCulture);
            }
        }

        /// <summary>
        ///   Save path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDestination {
            get {
                return ResourceManager.GetString("MenuDestination", resourceCulture);
            }
        }

        /// <summary>
        ///   Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDetails {
            get {
                return ResourceManager.GetString("MenuDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDown {
            get {
                return ResourceManager.GetString("MenuDown", resourceCulture);
            }
        }

        /// <summary>
        ///   dpi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDpi {
            get {
                return ResourceManager.GetString("MenuDpi", resourceCulture);
            }
        }

        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Security に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEncryption {
            get {
                return ResourceManager.GetString("MenuEncryption", resourceCulture);
            }
        }

        /// <summary>
        ///   Encrypt the PDF with password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEncryptionEnabled {
            get {
                return ResourceManager.GetString("MenuEncryptionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEncryptionMethod {
            get {
                return ResourceManager.GetString("MenuEncryptionMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Extract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExtract {
            get {
                return ResourceManager.GetString("MenuExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   All pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExtractAll {
            get {
                return ResourceManager.GetString("MenuExtractAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Extract with other settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExtractOthers {
            get {
                return ResourceManager.GetString("MenuExtractOthers", resourceCulture);
            }
        }

        /// <summary>
        ///   Specified range に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExtractRange {
            get {
                return ResourceManager.GetString("MenuExtractRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Selected pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExtractSelected {
            get {
                return ResourceManager.GetString("MenuExtractSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFilename {
            get {
                return ResourceManager.GetString("MenuFilename", resourceCulture);
            }
        }

        /// <summary>
        ///   Filesize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFilesize {
            get {
                return ResourceManager.GetString("MenuFilesize", resourceCulture);
            }
        }

        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFiletype {
            get {
                return ResourceManager.GetString("MenuFiletype", resourceCulture);
            }
        }

        /// <summary>
        ///   Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFormat {
            get {
                return ResourceManager.GetString("MenuFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Frame only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFrameOnly {
            get {
                return ResourceManager.GetString("MenuFrameOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Insert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsert {
            get {
                return ResourceManager.GetString("MenuInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   Insert at the end に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsertBack {
            get {
                return ResourceManager.GetString("MenuInsertBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Insert at the beginning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsertFront {
            get {
                return ResourceManager.GetString("MenuInsertFront", resourceCulture);
            }
        }

        /// <summary>
        ///   Insert at other position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsertOthers {
            get {
                return ResourceManager.GetString("MenuInsertOthers", resourceCulture);
            }
        }

        /// <summary>
        ///   Insert position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsertPosition {
            get {
                return ResourceManager.GetString("MenuInsertPosition", resourceCulture);
            }
        }

        /// <summary>
        ///   Keywords に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuKeywords {
            get {
                return ResourceManager.GetString("MenuKeywords", resourceCulture);
            }
        }

        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Last updated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuLastWriteTime {
            get {
                return ResourceManager.GetString("MenuLastWriteTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuLayout {
            get {
                return ResourceManager.GetString("MenuLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Metadata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMetadata {
            get {
                return ResourceManager.GetString("MenuMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMoveNext {
            get {
                return ResourceManager.GetString("MenuMoveNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMovePrevious {
            get {
                return ResourceManager.GetString("MenuMovePrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOk {
            get {
                return ResourceManager.GetString("MenuOk", resourceCulture);
            }
        }

        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Open with password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpenWithPassword {
            get {
                return ResourceManager.GetString("MenuOpenWithPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Operations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOperations {
            get {
                return ResourceManager.GetString("MenuOperations", resourceCulture);
            }
        }

        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Others に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOthers {
            get {
                return ResourceManager.GetString("MenuOthers", resourceCulture);
            }
        }

        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOwnerPassword {
            get {
                return ResourceManager.GetString("MenuOwnerPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Page count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPageCount {
            get {
                return ResourceManager.GetString("MenuPageCount", resourceCulture);
            }
        }

        /// <summary>
        ///   PDF version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPdfVersion {
            get {
                return ResourceManager.GetString("MenuPdfVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Beginning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPositionFirst {
            get {
                return ResourceManager.GetString("MenuPositionFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   End に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPositionLast {
            get {
                return ResourceManager.GetString("MenuPositionLast", resourceCulture);
            }
        }

        /// <summary>
        ///   Selected position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPositionSelected {
            get {
                return ResourceManager.GetString("MenuPositionSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Behind the number of に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPositionSpecified {
            get {
                return ResourceManager.GetString("MenuPositionSpecified", resourceCulture);
            }
        }

        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPreview {
            get {
                return ResourceManager.GetString("MenuPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Producer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuProducer {
            get {
                return ResourceManager.GetString("MenuProducer", resourceCulture);
            }
        }

        /// <summary>
        ///   Recent files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRecent {
            get {
                return ResourceManager.GetString("MenuRecent", resourceCulture);
            }
        }

        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }

        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRedraw {
            get {
                return ResourceManager.GetString("MenuRedraw", resourceCulture);
            }
        }

        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Remove other pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRemoveOthers {
            get {
                return ResourceManager.GetString("MenuRemoveOthers", resourceCulture);
            }
        }

        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRotateLeft {
            get {
                return ResourceManager.GetString("MenuRotateLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRotateRight {
            get {
                return ResourceManager.GetString("MenuRotateRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelect {
            get {
                return ResourceManager.GetString("MenuSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Select all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Cancel selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelectClear {
            get {
                return ResourceManager.GetString("MenuSelectClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Flip selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelectFlip {
            get {
                return ResourceManager.GetString("MenuSelectFlip", resourceCulture);
            }
        }

        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSetting {
            get {
                return ResourceManager.GetString("MenuSetting", resourceCulture);
            }
        }

        /// <summary>
        ///   Use owner password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSharePassword {
            get {
                return ResourceManager.GetString("MenuSharePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Save as a separate file per page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSplit {
            get {
                return ResourceManager.GetString("MenuSplit", resourceCulture);
            }
        }

        /// <summary>
        ///   Subject に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSubject {
            get {
                return ResourceManager.GetString("MenuSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   Summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSummary {
            get {
                return ResourceManager.GetString("MenuSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Target pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTarget {
            get {
                return ResourceManager.GetString("MenuTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }

        /// <summary>
        ///   Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUp {
            get {
                return ResourceManager.GetString("MenuUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Check update at launching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUpdate {
            get {
                return ResourceManager.GetString("MenuUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUserPassword {
            get {
                return ResourceManager.GetString("MenuUserPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuVersion {
            get {
                return ResourceManager.GetString("MenuVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   One column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuViewOneColumn {
            get {
                return ResourceManager.GetString("MenuViewOneColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Single page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuViewSinglePage {
            get {
                return ResourceManager.GetString("MenuViewSinglePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Two column (left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuViewTwoColumnLeft {
            get {
                return ResourceManager.GetString("MenuViewTwoColumnLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Two column (right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuViewTwoColumnRight {
            get {
                return ResourceManager.GetString("MenuViewTwoColumnRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Two page (left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuViewTwoPageLeft {
            get {
                return ResourceManager.GetString("MenuViewTwoPageLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Two page (right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuViewTwoPageRight {
            get {
                return ResourceManager.GetString("MenuViewTwoPageRight", resourceCulture);
            }
        }

        /// <summary>
        ///   ZoomIn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuZoomIn {
            get {
                return ResourceManager.GetString("MenuZoomIn", resourceCulture);
            }
        }

        /// <summary>
        ///   ZoomOut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuZoomOut {
            get {
                return ResourceManager.GetString("MenuZoomOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Loading {0} ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLoading {
            get {
                return ResourceManager.GetString("MessageLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   PDF is modified. Do you want to overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageOverwrite {
            get {
                return ResourceManager.GetString("MessageOverwrite", resourceCulture);
            }
        }

        /// <summary>
        ///   {0} pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePage {
            get {
                return ResourceManager.GetString("MessagePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Please enter the owner password for opening and editing {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePassword {
            get {
                return ResourceManager.GetString("MessagePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to parse the removal range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRangeError {
            get {
                return ResourceManager.GetString("MessageRangeError", resourceCulture);
            }
        }

        /// <summary>
        ///   e.g. 1,2,4-7,9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRangeExample {
            get {
                return ResourceManager.GetString("MessageRangeExample", resourceCulture);
            }
        }

        /// <summary>
        ///   Saved at {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaved {
            get {
                return ResourceManager.GetString("MessageSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Saving to {0} ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaving {
            get {
                return ResourceManager.GetString("MessageSaving", resourceCulture);
            }
        }

        /// <summary>
        ///   {0} pages selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSelection {
            get {
                return ResourceManager.GetString("MessageSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   {0} pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageTotalPage {
            get {
                return ResourceManager.GetString("MessageTotalPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Encryption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleEncryption {
            get {
                return ResourceManager.GetString("TitleEncryption", resourceCulture);
            }
        }

        /// <summary>
        ///   Extraction details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleExtract {
            get {
                return ResourceManager.GetString("TitleExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Insertion details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleInsert {
            get {
                return ResourceManager.GetString("TitleInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   PDF Metadata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleMetadata {
            get {
                return ResourceManager.GetString("TitleMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Open file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleOpen {
            get {
                return ResourceManager.GetString("TitleOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Input password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitlePassword {
            get {
                return ResourceManager.GetString("TitlePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   {0} ({1}/{2} page) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitlePreview {
            get {
                return ResourceManager.GetString("TitlePreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Removal details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleRemove {
            get {
                return ResourceManager.GetString("TitleRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSaveAs {
            get {
                return ResourceManager.GetString("TitleSaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   CubePDF Utility settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSetting {
            get {
                return ResourceManager.GetString("TitleSetting", resourceCulture);
            }
        }

        /// <summary>
        ///   Extract the selected pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipExtract {
            get {
                return ResourceManager.GetString("TooltipExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Insert behind selected position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipInsert {
            get {
                return ResourceManager.GetString("TooltipInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   PDF document metadata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipMetadata {
            get {
                return ResourceManager.GetString("TooltipMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Remove the selected pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipRemove {
            get {
                return ResourceManager.GetString("TooltipRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipSave {
            get {
                return ResourceManager.GetString("TooltipSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Bytes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnitByte {
            get {
                return ResourceManager.GetString("UnitByte", resourceCulture);
            }
        }

        /// <summary>
        ///   β に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionSuffix {
            get {
                return ResourceManager.GetString("VersionSuffix", resourceCulture);
            }
        }
    }
}
