//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.Converter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.Converter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message digest of the source file does not match..
        /// </summary>
        internal static string ErrorDigest {
            get {
                return ResourceManager.GetString("ErrorDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghostscript error ({0:D}).
        /// </summary>
        internal static string ErrorGhostscript {
            get {
                return ResourceManager.GetString("ErrorGhostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot contain any of the following characters.
        /// </summary>
        internal static string ErrorInvalidChars {
            get {
                return ResourceManager.GetString("ErrorInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the owner password of the PDF file to be merged in the Security tab..
        /// </summary>
        internal static string ErrorMergePassword {
            get {
                return ResourceManager.GetString("ErrorMergePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner password is empty or does not match the confirmation. Please check your password and confirmation again..
        /// </summary>
        internal static string ErrorOwnerPassword {
            get {
                return ResourceManager.GetString("ErrorOwnerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file not specified. Please check if CubePDF was executed through the normal procedure..
        /// </summary>
        internal static string ErrorSource {
            get {
                return ResourceManager.GetString("ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password is empty or does not match the confirmation. Please check the user password or enable the &quot;Use owner password&quot; checkbox..
        /// </summary>
        internal static string ErrorUserPassword {
            get {
                return ResourceManager.GetString("ErrorUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP files.
        /// </summary>
        internal static string FilterBmp {
            get {
                return ResourceManager.GetString("FilterBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPS files.
        /// </summary>
        internal static string FilterEps {
            get {
                return ResourceManager.GetString("FilterEps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files.
        /// </summary>
        internal static string FilterExecutable {
            get {
                return ResourceManager.GetString("FilterExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG files.
        /// </summary>
        internal static string FilterJpeg {
            get {
                return ResourceManager.GetString("FilterJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files.
        /// </summary>
        internal static string FilterPdf {
            get {
                return ResourceManager.GetString("FilterPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG files.
        /// </summary>
        internal static string FilterPng {
            get {
                return ResourceManager.GetString("FilterPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS files.
        /// </summary>
        internal static string FilterPs {
            get {
                return ResourceManager.GetString("FilterPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF files.
        /// </summary>
        internal static string FilterTiff {
            get {
                return ResourceManager.GetString("FilterTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string MenuAuto {
            get {
                return ResourceManager.GetString("MenuAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        internal static string MenuGrayscale {
            get {
                return ResourceManager.GetString("MenuGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string MenuLandscape {
            get {
                return ResourceManager.GetString("MenuLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge at the beginning.
        /// </summary>
        internal static string MenuMergeHead {
            get {
                return ResourceManager.GetString("MenuMergeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge at the end.
        /// </summary>
        internal static string MenuMergeTail {
            get {
                return ResourceManager.GetString("MenuMergeTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome.
        /// </summary>
        internal static string MenuMonochrome {
            get {
                return ResourceManager.GetString("MenuMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MenuNone {
            get {
                return ResourceManager.GetString("MenuNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One column.
        /// </summary>
        internal static string MenuOneColumn {
            get {
                return ResourceManager.GetString("MenuOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory.
        /// </summary>
        internal static string MenuOpenDirectory {
            get {
                return ResourceManager.GetString("MenuOpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string MenuOthers {
            get {
                return ResourceManager.GetString("MenuOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string MenuOverwrite {
            get {
                return ResourceManager.GetString("MenuOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string MenuPortrait {
            get {
                return ResourceManager.GetString("MenuPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        internal static string MenuRgb {
            get {
                return ResourceManager.GetString("MenuRgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single page.
        /// </summary>
        internal static string MenuSinglePage {
            get {
                return ResourceManager.GetString("MenuSinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two column (left).
        /// </summary>
        internal static string MenuTwoColumnLeft {
            get {
                return ResourceManager.GetString("MenuTwoColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two column (right).
        /// </summary>
        internal static string MenuTwoColumnRight {
            get {
                return ResourceManager.GetString("MenuTwoColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two page (left).
        /// </summary>
        internal static string MenuTwoPageLeft {
            get {
                return ResourceManager.GetString("MenuTwoPageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two page (right).
        /// </summary>
        internal static string MenuTwoPageRight {
            get {
                return ResourceManager.GetString("MenuTwoPageRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string TitleSelectDestination {
            get {
                return ResourceManager.GetString("TitleSelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source file.
        /// </summary>
        internal static string TitleSelectSource {
            get {
                return ResourceManager.GetString("TitleSelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user program.
        /// </summary>
        internal static string TitleSelectUserProgram {
            get {
                return ResourceManager.GetString("TitleSelectUserProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        internal static string WarnExists {
            get {
                return ResourceManager.GetString("WarnExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to merge at the beginning of the existing file?.
        /// </summary>
        internal static string WarnMergeHead {
            get {
                return ResourceManager.GetString("WarnMergeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to merge at the end of the existing file?.
        /// </summary>
        internal static string WarnMergeTail {
            get {
                return ResourceManager.GetString("WarnMergeTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the file?.
        /// </summary>
        internal static string WarnOverwrite {
            get {
                return ResourceManager.GetString("WarnOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some value is entered in the Title, Author, Subject, or Keywords field. Do you want to save the settings?.
        /// </summary>
        internal static string WarnSaveSettings {
            get {
                return ResourceManager.GetString("WarnSaveSettings", resourceCulture);
            }
        }
    }
}
