//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.App.Converter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.App.Converter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BMP files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterBmp {
            get {
                return ResourceManager.GetString("FilterBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EPS files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterEps {
            get {
                return ResourceManager.GetString("FilterEps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterExecutable {
            get {
                return ResourceManager.GetString("FilterExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JPEG files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterJpeg {
            get {
                return ResourceManager.GetString("FilterJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPdf {
            get {
                return ResourceManager.GetString("FilterPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PNG files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPng {
            get {
                return ResourceManager.GetString("FilterPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PS files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPs {
            get {
                return ResourceManager.GetString("FilterPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TIFF files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterTiff {
            get {
                return ResourceManager.GetString("FilterTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Auto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuAuto {
            get {
                return ResourceManager.GetString("MenuAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuJapanese {
            get {
                return ResourceManager.GetString("MenuJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Landscape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuLandscape {
            get {
                return ResourceManager.GetString("MenuLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge head に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMergeHead {
            get {
                return ResourceManager.GetString("MenuMergeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge tail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMergeTail {
            get {
                return ResourceManager.GetString("MenuMergeTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuNone {
            get {
                return ResourceManager.GetString("MenuNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOneColumn {
            get {
                return ResourceManager.GetString("MenuOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpenFolder {
            get {
                return ResourceManager.GetString("MenuOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Others に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOthers {
            get {
                return ResourceManager.GetString("MenuOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOverwrite {
            get {
                return ResourceManager.GetString("MenuOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portrait に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPortrait {
            get {
                return ResourceManager.GetString("MenuPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSinglePage {
            get {
                return ResourceManager.GetString("MenuSinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two column (left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTwoColumnLeft {
            get {
                return ResourceManager.GetString("MenuTwoColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two column (right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTwoColumnRight {
            get {
                return ResourceManager.GetString("MenuTwoColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two page (left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTwoPageLeft {
            get {
                return ResourceManager.GetString("MenuTwoPageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two page (right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTwoPageRight {
            get {
                return ResourceManager.GetString("MenuTwoPageRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleBroseDestination {
            get {
                return ResourceManager.GetString("TitleBroseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select user program に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleBroseUserProgram {
            get {
                return ResourceManager.GetString("TitleBroseUserProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select source file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleBrowseSource {
            get {
                return ResourceManager.GetString("TitleBrowseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubePDF error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubePDF warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
    }
}
