//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.ImageEx.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.ImageEx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} のファイル構造を解析中です... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BeginMessage {
            get {
                return ResourceManager.GetString("BeginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理をキャンセルしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelMessage {
            get {
                return ResourceManager.GetString("CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CloseButton {
            get {
                object obj = ResourceManager.GetObject("CloseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DragDrop {
            get {
                object obj = ResourceManager.GetObject("DragDrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   PDF ファイルをドラッグ&amp;ドロップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DragDropMessage {
            get {
                return ResourceManager.GetString("DragDropMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ({1} ページ) から {2} 個の画像を抽出しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndMessage {
            get {
                return ResourceManager.GetString("EndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HeaderImage {
            get {
                object obj = ResourceManager.GetObject("HeaderImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HeaderLogo {
            get {
                object obj = ResourceManager.GetObject("HeaderLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   プレビュー画面を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreviewMenu {
            get {
                return ResourceManager.GetString("PreviewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} の {1}/{2} ページ目から画像を抽出しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessMessage {
            get {
                return ResourceManager.GetString("ProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択項目を一覧から削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveMenu {
            get {
                return ResourceManager.GetString("RemoveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出画像を保存するフォルダを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択項目を保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全ての項目を選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectAllMenu {
            get {
                return ResourceManager.GetString("SelectAllMenu", resourceCulture);
            }
        }
    }
}
