//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.Pages.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.Pages.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnDate {
            get {
                return ResourceManager.GetString("ColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnLength {
            get {
                return ResourceManager.GetString("ColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnPages {
            get {
                return ResourceManager.GetString("ColumnPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPdf {
            get {
                return ResourceManager.GetString("FilterPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加可能なファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterSupported {
            get {
                return ResourceManager.GetString("FilterSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HeaderTitle {
            get {
                object obj = ResourceManager.GetObject("HeaderTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   下へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDown {
            get {
                return ResourceManager.GetString("MenuDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPreview {
            get {
                return ResourceManager.GetString("MenuPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルリストから削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUp {
            get {
                return ResourceManager.GetString("MenuUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubePDF Page について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageAbout {
            get {
                return ResourceManager.GetString("MessageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} はパスワードで保護されています。編集するためには管理用パスワードを入力して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePassword {
            get {
                return ResourceManager.GetString("MessagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を実行中です... - {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleBusy {
            get {
                return ResourceManager.GetString("TitleBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結合したファイルの保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleMerge {
            get {
                return ResourceManager.GetString("TitleMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分割したファイルを保存するフォルダを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSplit {
            get {
                return ResourceManager.GetString("TitleSplit", resourceCulture);
            }
        }
    }
}
