//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.Pages.Properties {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.Pages.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Last updated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnDate {
            get {
                return ResourceManager.GetString("ColumnDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Filesize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnLength {
            get {
                return ResourceManager.GetString("ColumnLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }

        /// <summary>
        ///   Pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnPages {
            get {
                return ResourceManager.GetString("ColumnPages", resourceCulture);
            }
        }

        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }

        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }

        /// <summary>
        ///   PDF files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPdf {
            get {
                return ResourceManager.GetString("FilterPdf", resourceCulture);
            }
        }

        /// <summary>
        ///   All supported files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterSupported {
            get {
                return ResourceManager.GetString("FilterSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HeaderTitle {
            get {
                object obj = ResourceManager.GetObject("HeaderTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDown {
            get {
                return ResourceManager.GetString("MenuDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPreview {
            get {
                return ResourceManager.GetString("MenuPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Remove from file list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUp {
            get {
                return ResourceManager.GetString("MenuUp", resourceCulture);
            }
        }

        /// <summary>
        ///   About CubePDF Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageAbout {
            get {
                return ResourceManager.GetString("MessageAbout", resourceCulture);
            }
        }

        /// <summary>
        ///   {0} is protected. Enter the owner password to edit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePassword {
            get {
                return ResourceManager.GetString("MessagePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Add files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Processing... - {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleBusy {
            get {
                return ResourceManager.GetString("TitleBusy", resourceCulture);
            }
        }

        /// <summary>
        ///   Save merged file as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleMerge {
            get {
                return ResourceManager.GetString("TitleMerge", resourceCulture);
            }
        }

        /// <summary>
        ///   Select a folder to save the split files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSplit {
            get {
                return ResourceManager.GetString("TitleSplit", resourceCulture);
            }
        }
    }
}
