//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.App.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.App.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPdf {
            get {
                return ResourceManager.GetString("FilterPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuEncryption {
            get {
                return ResourceManager.GetString("MenuEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExtract {
            get {
                return ResourceManager.GetString("MenuExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extraction details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExtractOthers {
            get {
                return ResourceManager.GetString("MenuExtractOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsert {
            get {
                return ResourceManager.GetString("MenuInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert at the end に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsertBack {
            get {
                return ResourceManager.GetString("MenuInsertBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert at the beginning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsertFront {
            get {
                return ResourceManager.GetString("MenuInsertFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insertion details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuInsertOthers {
            get {
                return ResourceManager.GetString("MenuInsertOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metadata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMetadata {
            get {
                return ResourceManager.GetString("MenuMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMoveNext {
            get {
                return ResourceManager.GetString("MenuMoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMovePrevious {
            get {
                return ResourceManager.GetString("MenuMovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRecent {
            get {
                return ResourceManager.GetString("MenuRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removal details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRemoveRange {
            get {
                return ResourceManager.GetString("MenuRemoveRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRotateLeft {
            get {
                return ResourceManager.GetString("MenuRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRotateRight {
            get {
                return ResourceManager.GetString("MenuRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelect {
            get {
                return ResourceManager.GetString("MenuSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelectClear {
            get {
                return ResourceManager.GetString("MenuSelectClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelectFlip {
            get {
                return ResourceManager.GetString("MenuSelectFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZoomIn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuZoomIn {
            get {
                return ResourceManager.GetString("MenuZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZoomOut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuZoomOut {
            get {
                return ResourceManager.GetString("MenuZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading {0} ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLoading {
            get {
                return ResourceManager.GetString("MessageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePage {
            get {
                return ResourceManager.GetString("MessagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving to {0} ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaving {
            get {
                return ResourceManager.GetString("MessageSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} pages selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSelection {
            get {
                return ResourceManager.GetString("MessageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleOpen {
            get {
                return ResourceManager.GetString("TitleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSaveAs {
            get {
                return ResourceManager.GetString("TitleSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract the selected pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipExtract {
            get {
                return ResourceManager.GetString("TooltipExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert behind selected position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipInsert {
            get {
                return ResourceManager.GetString("TooltipInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF document metadata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipMetadata {
            get {
                return ResourceManager.GetString("TooltipMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove the selected pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipRemove {
            get {
                return ResourceManager.GetString("TooltipRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooltipSave {
            get {
                return ResourceManager.GetString("TooltipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   β に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionSuffix {
            get {
                return ResourceManager.GetString("VersionSuffix", resourceCulture);
            }
        }
    }
}
