namespace Cube.Pdf.Clip
{
    partial class MainWindow
    {
        private System.ComponentModel.IContainer components = null;

        /* ----------------------------------------------------------------- */
        ///
        /// Dispose
        ///
        /// <summary>
        /// Releases the unmanaged resources used by the object and
        /// optionally releases the managed resources.
        /// </summary>
        ///
        /// <param name="disposing">
        /// true to release both managed and unmanaged resources;
        /// false to release only unmanaged resources.
        /// </param>
        ///
        /* ----------------------------------------------------------------- */
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Generated by designer

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainWindow));
            this.LayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.FooterPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.ExitButton = new Cube.Forms.Controls.Button();
            this.SaveButton = new Cube.Forms.Controls.Button();
            this.SourcePanel = new System.Windows.Forms.TableLayoutPanel();
            this.SourceLabel = new System.Windows.Forms.Label();
            this.SourceTextBox = new System.Windows.Forms.TextBox();
            this.OpenButton = new Cube.Forms.Controls.Button();
            this.ClipPanel = new System.Windows.Forms.TableLayoutPanel();
            this.ToolsPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.AttachButton = new Cube.Forms.Controls.Button();
            this.DetachButton = new Cube.Forms.Controls.Button();
            this.ResetButton = new Cube.Forms.Controls.Button();
            this.ClipListView = new Cube.Pdf.Clip.ClipListControl();
            this.VersionButton = new System.Windows.Forms.PictureBox();
            this.MainBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.LayoutPanel.SuspendLayout();
            this.FooterPanel.SuspendLayout();
            this.SourcePanel.SuspendLayout();
            this.ClipPanel.SuspendLayout();
            this.ToolsPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ClipListView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.VersionButton)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.MainBindingSource)).BeginInit();
            this.SuspendLayout();
            //
            // LayoutPanel
            //
            this.LayoutPanel.ColumnCount = 1;
            this.LayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.LayoutPanel.Controls.Add(this.FooterPanel, 0, 3);
            this.LayoutPanel.Controls.Add(this.SourcePanel, 0, 1);
            this.LayoutPanel.Controls.Add(this.ClipPanel, 0, 2);
            this.LayoutPanel.Controls.Add(this.VersionButton, 0, 0);
            this.LayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.LayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.LayoutPanel.Name = "LayoutPanel";
            this.LayoutPanel.RowCount = 4;
            this.LayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.LayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.LayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.LayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.LayoutPanel.Size = new System.Drawing.Size(684, 311);
            this.LayoutPanel.TabIndex = 0;
            //
            // FooterPanel
            //
            this.FooterPanel.AllowDrop = true;
            this.FooterPanel.Controls.Add(this.ExitButton);
            this.FooterPanel.Controls.Add(this.SaveButton);
            this.FooterPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.FooterPanel.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.FooterPanel.Location = new System.Drawing.Point(0, 251);
            this.FooterPanel.Margin = new System.Windows.Forms.Padding(0);
            this.FooterPanel.Name = "FooterPanel";
            this.FooterPanel.Padding = new System.Windows.Forms.Padding(0, 9, 9, 0);
            this.FooterPanel.Size = new System.Drawing.Size(684, 60);
            this.FooterPanel.TabIndex = 7;
            //
            // ExitButton
            //
            this.ExitButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.ExitButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.ExitButton.FlatAppearance.BorderColor = System.Drawing.Color.Gainsboro;
            this.ExitButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.ExitButton.ForeColor = System.Drawing.Color.White;
            this.ExitButton.Location = new System.Drawing.Point(572, 12);
            this.ExitButton.Name = "ExitButton";
            this.ExitButton.Size = new System.Drawing.Size(100, 35);
            this.ExitButton.TabIndex = 2;
            this.ExitButton.Text = "終了";
            this.ExitButton.UseVisualStyleBackColor = false;
            //
            // SaveButton
            //
            this.SaveButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(39)))), ((int)(((byte)(45)))));
            this.SaveButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.SaveButton.FlatAppearance.BorderColor = System.Drawing.Color.Gainsboro;
            this.SaveButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.SaveButton.ForeColor = System.Drawing.Color.White;
            this.SaveButton.Location = new System.Drawing.Point(431, 12);
            this.SaveButton.Name = "SaveButton";
            this.SaveButton.Size = new System.Drawing.Size(135, 35);
            this.SaveButton.TabIndex = 3;
            this.SaveButton.Text = "保存 (&S)";
            this.SaveButton.UseVisualStyleBackColor = false;
            //
            // SourcePanel
            //
            this.SourcePanel.ColumnCount = 3;
            this.SourcePanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 80F));
            this.SourcePanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.SourcePanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 82F));
            this.SourcePanel.Controls.Add(this.SourceLabel, 0, 0);
            this.SourcePanel.Controls.Add(this.SourceTextBox, 1, 0);
            this.SourcePanel.Controls.Add(this.OpenButton, 2, 0);
            this.SourcePanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SourcePanel.Location = new System.Drawing.Point(0, 35);
            this.SourcePanel.Margin = new System.Windows.Forms.Padding(0);
            this.SourcePanel.Name = "SourcePanel";
            this.SourcePanel.RowCount = 1;
            this.SourcePanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.SourcePanel.Size = new System.Drawing.Size(684, 35);
            this.SourcePanel.TabIndex = 5;
            //
            // SourceLabel
            //
            this.SourceLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.SourceLabel.AutoSize = true;
            this.SourceLabel.Location = new System.Drawing.Point(6, 10);
            this.SourceLabel.Name = "SourceLabel";
            this.SourceLabel.Size = new System.Drawing.Size(68, 15);
            this.SourceLabel.TabIndex = 0;
            this.SourceLabel.Text = "PDF ファイル";
            //
            // SourceTextBox
            //
            this.SourceTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.SourceTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.MainBindingSource, "Source", true));
            this.SourceTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SourceTextBox.Location = new System.Drawing.Point(86, 6);
            this.SourceTextBox.Margin = new System.Windows.Forms.Padding(6);
            this.SourceTextBox.Name = "SourceTextBox";
            this.SourceTextBox.ReadOnly = true;
            this.SourceTextBox.Size = new System.Drawing.Size(510, 23);
            this.SourceTextBox.TabIndex = 1;
            //
            // OpenButton
            //
            this.OpenButton.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.OpenButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(39)))), ((int)(((byte)(45)))));
            this.OpenButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(37)))), ((int)(((byte)(43)))));
            this.OpenButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.OpenButton.ForeColor = System.Drawing.Color.White;
            this.OpenButton.Location = new System.Drawing.Point(602, 6);
            this.OpenButton.Margin = new System.Windows.Forms.Padding(0);
            this.OpenButton.Name = "OpenButton";
            this.OpenButton.Size = new System.Drawing.Size(70, 23);
            this.OpenButton.TabIndex = 2;
            this.OpenButton.Text = "...";
            this.OpenButton.UseVisualStyleBackColor = false;
            //
            // ClipPanel
            //
            this.ClipPanel.ColumnCount = 2;
            this.ClipPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ClipPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 124F));
            this.ClipPanel.Controls.Add(this.ToolsPanel, 1, 0);
            this.ClipPanel.Controls.Add(this.ClipListView, 0, 0);
            this.ClipPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ClipPanel.Location = new System.Drawing.Point(0, 70);
            this.ClipPanel.Margin = new System.Windows.Forms.Padding(0);
            this.ClipPanel.Name = "ClipPanel";
            this.ClipPanel.RowCount = 1;
            this.ClipPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ClipPanel.Size = new System.Drawing.Size(684, 181);
            this.ClipPanel.TabIndex = 6;
            //
            // ToolsPanel
            //
            this.ToolsPanel.AllowDrop = true;
            this.ToolsPanel.Controls.Add(this.AttachButton);
            this.ToolsPanel.Controls.Add(this.DetachButton);
            this.ToolsPanel.Controls.Add(this.ResetButton);
            this.ToolsPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ToolsPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.ToolsPanel.Location = new System.Drawing.Point(560, 0);
            this.ToolsPanel.Margin = new System.Windows.Forms.Padding(0);
            this.ToolsPanel.Name = "ToolsPanel";
            this.ToolsPanel.Padding = new System.Windows.Forms.Padding(9, 0, 9, 0);
            this.ToolsPanel.Size = new System.Drawing.Size(124, 181);
            this.ToolsPanel.TabIndex = 3;
            //
            // AttachButton
            //
            this.AttachButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
            this.AttachButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(49)))), ((int)(((byte)(49)))));
            this.AttachButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.AttachButton.ForeColor = System.Drawing.Color.White;
            this.AttachButton.Location = new System.Drawing.Point(12, 0);
            this.AttachButton.Margin = new System.Windows.Forms.Padding(3, 0, 3, 3);
            this.AttachButton.Name = "AttachButton";
            this.AttachButton.Size = new System.Drawing.Size(100, 30);
            this.AttachButton.TabIndex = 0;
            this.AttachButton.Text = "追加 (&N) ...";
            this.AttachButton.UseVisualStyleBackColor = false;
            //
            // DetachButton
            //
            this.DetachButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
            this.DetachButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(49)))), ((int)(((byte)(49)))));
            this.DetachButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.DetachButton.ForeColor = System.Drawing.Color.White;
            this.DetachButton.Location = new System.Drawing.Point(12, 36);
            this.DetachButton.Name = "DetachButton";
            this.DetachButton.Size = new System.Drawing.Size(100, 30);
            this.DetachButton.TabIndex = 3;
            this.DetachButton.Text = "削除 (&D)";
            this.DetachButton.UseVisualStyleBackColor = false;
            //
            // ResetButton
            //
            this.ResetButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
            this.ResetButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(49)))), ((int)(((byte)(49)))));
            this.ResetButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.ResetButton.ForeColor = System.Drawing.Color.White;
            this.ResetButton.Location = new System.Drawing.Point(12, 72);
            this.ResetButton.Name = "ResetButton";
            this.ResetButton.Size = new System.Drawing.Size(100, 30);
            this.ResetButton.TabIndex = 4;
            this.ResetButton.Text = "リセット (&R)";
            this.ResetButton.UseVisualStyleBackColor = false;
            //
            // ClipListView
            //
            this.ClipListView.AllowUserToAddRows = false;
            this.ClipListView.AllowUserToDeleteRows = false;
            this.ClipListView.AllowUserToResizeRows = false;
            this.ClipListView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.ClipListView.BackgroundColor = System.Drawing.SystemColors.Window;
            this.ClipListView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.ClipListView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.ClipListView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.ClipListView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.ClipListView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ClipListView.GridColor = System.Drawing.SystemColors.Control;
            this.ClipListView.Location = new System.Drawing.Point(0, 0);
            this.ClipListView.Margin = new System.Windows.Forms.Padding(0);
            this.ClipListView.Name = "ClipListView";
            this.ClipListView.ReadOnly = true;
            this.ClipListView.RowHeadersVisible = false;
            this.ClipListView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.ClipListView.Size = new System.Drawing.Size(560, 181);
            this.ClipListView.TabIndex = 4;
            //
            // VersionButton
            //
            this.VersionButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(39)))), ((int)(((byte)(45)))));
            this.VersionButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.VersionButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.VersionButton.Image = global::Cube.Pdf.Clip.Properties.Resources.HeaderImage;
            this.VersionButton.Location = new System.Drawing.Point(0, 0);
            this.VersionButton.Margin = new System.Windows.Forms.Padding(0);
            this.VersionButton.Name = "VersionButton";
            this.VersionButton.Size = new System.Drawing.Size(684, 35);
            this.VersionButton.TabIndex = 8;
            this.VersionButton.TabStop = false;
            //
            // MainBindingSource
            //
            this.MainBindingSource.DataSource = typeof(Cube.Pdf.Clip.MainViewModel);
            //
            // MainWindow
            //
            this.AllowDrop = true;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(684, 311);
            this.Controls.Add(this.LayoutPanel);
            this.Font = new System.Drawing.Font("Meiryo UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.MinimumSize = new System.Drawing.Size(510, 280);
            this.Name = "MainWindow";
            this.Text = "CubePDF Clip";
            this.LayoutPanel.ResumeLayout(false);
            this.FooterPanel.ResumeLayout(false);
            this.SourcePanel.ResumeLayout(false);
            this.SourcePanel.PerformLayout();
            this.ClipPanel.ResumeLayout(false);
            this.ToolsPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ClipListView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.VersionButton)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.MainBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel LayoutPanel;
        private System.Windows.Forms.TableLayoutPanel SourcePanel;
        private System.Windows.Forms.TableLayoutPanel ClipPanel;
        private System.Windows.Forms.FlowLayoutPanel ToolsPanel;
        private System.Windows.Forms.FlowLayoutPanel FooterPanel;
        private System.Windows.Forms.Label SourceLabel;
        private System.Windows.Forms.TextBox SourceTextBox;
        private System.Windows.Forms.PictureBox VersionButton;
        private Cube.Forms.Controls.Button AttachButton;
        private Cube.Forms.Controls.Button DetachButton;
        private Cube.Forms.Controls.Button ResetButton;
        private Cube.Forms.Controls.Button ExitButton;
        private Cube.Forms.Controls.Button SaveButton;
        private Cube.Forms.Controls.Button OpenButton;
        private ClipListControl ClipListView;
        private System.Windows.Forms.BindingSource MainBindingSource;
    }
}

