namespace Cube.Pdf.Pages
{
    partial class MainWindow
    {
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Generated by designer

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainWindow));
            this.RootPanel = new System.Windows.Forms.TableLayoutPanel();
            this.FilePanel = new System.Windows.Forms.TableLayoutPanel();
            this.FileListView = new Cube.Pdf.Pages.FileListControl();
            this.RightPanel = new System.Windows.Forms.TableLayoutPanel();
            this.AddButton = new Cube.Forms.Controls.Button();
            this.UpButton = new Cube.Forms.Controls.Button();
            this.DownButton = new Cube.Forms.Controls.Button();
            this.RemoveButton = new Cube.Forms.Controls.Button();
            this.ClearButton = new Cube.Forms.Controls.Button();
            this.HeaderPanel = new System.Windows.Forms.Panel();
            this.TitleButton = new System.Windows.Forms.PictureBox();
            this.FooterPanel = new System.Windows.Forms.TableLayoutPanel();
            this.MetadataButton = new Cube.Forms.Controls.Button();
            this.ExitButton = new Cube.Forms.Controls.Button();
            this.SplitButton = new Cube.Forms.Controls.Button();
            this.MainBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.MergeButton = new Cube.Forms.Controls.Button();
            this.RootPanel.SuspendLayout();
            this.FilePanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.FileListView)).BeginInit();
            this.RightPanel.SuspendLayout();
            this.HeaderPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TitleButton)).BeginInit();
            this.FooterPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.MainBindingSource)).BeginInit();
            this.SuspendLayout();
            //
            // RootPanel
            //
            resources.ApplyResources(this.RootPanel, "RootPanel");
            this.RootPanel.Controls.Add(this.FilePanel, 0, 1);
            this.RootPanel.Controls.Add(this.HeaderPanel, 0, 0);
            this.RootPanel.Controls.Add(this.FooterPanel, 0, 2);
            this.RootPanel.Name = "RootPanel";
            //
            // FilePanel
            //
            resources.ApplyResources(this.FilePanel, "FilePanel");
            this.FilePanel.Controls.Add(this.FileListView, 0, 0);
            this.FilePanel.Controls.Add(this.RightPanel, 1, 0);
            this.FilePanel.Name = "FilePanel";
            //
            // FileListView
            //
            resources.ApplyResources(this.FileListView, "FileListView");
            this.FileListView.AllowUserToAddRows = false;
            this.FileListView.AllowUserToDeleteRows = false;
            this.FileListView.AllowUserToResizeRows = false;
            this.FileListView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.FileListView.BackgroundColor = System.Drawing.SystemColors.Window;
            this.FileListView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.FileListView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.FileListView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.FileListView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.FileListView.GridColor = System.Drawing.SystemColors.Control;
            this.FileListView.Name = "FileListView";
            this.FileListView.ReadOnly = true;
            this.FileListView.RowHeadersVisible = false;
            this.FileListView.RowTemplate.Height = 21;
            this.FileListView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            //
            // RightPanel
            //
            resources.ApplyResources(this.RightPanel, "RightPanel");
            this.RightPanel.Controls.Add(this.AddButton, 1, 1);
            this.RightPanel.Controls.Add(this.UpButton, 1, 2);
            this.RightPanel.Controls.Add(this.DownButton, 1, 3);
            this.RightPanel.Controls.Add(this.RemoveButton, 1, 4);
            this.RightPanel.Controls.Add(this.ClearButton, 1, 5);
            this.RightPanel.Name = "RightPanel";
            //
            // AddButton
            //
            resources.ApplyResources(this.AddButton, "AddButton");
            this.AddButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(72)))), ((int)(((byte)(72)))));
            this.AddButton.FlatAppearance.BorderColor = System.Drawing.Color.Gray;
            this.AddButton.ForeColor = System.Drawing.Color.White;
            this.AddButton.Name = "AddButton";
            this.AddButton.UseVisualStyleBackColor = false;
            //
            // UpButton
            //
            resources.ApplyResources(this.UpButton, "UpButton");
            this.UpButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(72)))), ((int)(((byte)(72)))));
            this.UpButton.FlatAppearance.BorderColor = System.Drawing.Color.Gray;
            this.UpButton.ForeColor = System.Drawing.Color.White;
            this.UpButton.Name = "UpButton";
            this.UpButton.UseVisualStyleBackColor = false;
            //
            // DownButton
            //
            resources.ApplyResources(this.DownButton, "DownButton");
            this.DownButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(72)))), ((int)(((byte)(72)))));
            this.DownButton.FlatAppearance.BorderColor = System.Drawing.Color.Gray;
            this.DownButton.ForeColor = System.Drawing.Color.White;
            this.DownButton.Name = "DownButton";
            this.DownButton.UseVisualStyleBackColor = false;
            //
            // RemoveButton
            //
            resources.ApplyResources(this.RemoveButton, "RemoveButton");
            this.RemoveButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(72)))), ((int)(((byte)(72)))));
            this.RemoveButton.FlatAppearance.BorderColor = System.Drawing.Color.Gray;
            this.RemoveButton.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.Name = "RemoveButton";
            this.RemoveButton.UseVisualStyleBackColor = false;
            //
            // ClearButton
            //
            resources.ApplyResources(this.ClearButton, "ClearButton");
            this.ClearButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(72)))), ((int)(((byte)(72)))));
            this.ClearButton.FlatAppearance.BorderColor = System.Drawing.Color.Gray;
            this.ClearButton.ForeColor = System.Drawing.Color.White;
            this.ClearButton.Name = "ClearButton";
            this.ClearButton.UseVisualStyleBackColor = false;
            //
            // HeaderPanel
            //
            resources.ApplyResources(this.HeaderPanel, "HeaderPanel");
            this.HeaderPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(39)))), ((int)(((byte)(45)))));
            this.HeaderPanel.BackgroundImage = global::Cube.Pdf.Pages.Properties.Resources.Background;
            this.HeaderPanel.Controls.Add(this.TitleButton);
            this.HeaderPanel.Name = "HeaderPanel";
            //
            // TitleButton
            //
            resources.ApplyResources(this.TitleButton, "TitleButton");
            this.TitleButton.BackgroundImage = global::Cube.Pdf.Pages.Properties.Resources.Background;
            this.TitleButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.TitleButton.Image = global::Cube.Pdf.Pages.Properties.Resources.HeaderTitle;
            this.TitleButton.Name = "TitleButton";
            this.TitleButton.TabStop = false;
            //
            // FooterPanel
            //
            resources.ApplyResources(this.FooterPanel, "FooterPanel");
            this.FooterPanel.Controls.Add(this.MetadataButton, 1, 1);
            this.FooterPanel.Controls.Add(this.ExitButton, 5, 1);
            this.FooterPanel.Controls.Add(this.SplitButton, 4, 1);
            this.FooterPanel.Controls.Add(this.MergeButton, 3, 1);
            this.FooterPanel.Name = "FooterPanel";
            //
            // MetadataButton
            //
            resources.ApplyResources(this.MetadataButton, "MetadataButton");
            this.MetadataButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(72)))), ((int)(((byte)(72)))));
            this.MetadataButton.FlatAppearance.BorderColor = System.Drawing.Color.Gray;
            this.MetadataButton.ForeColor = System.Drawing.Color.White;
            this.MetadataButton.Name = "MetadataButton";
            this.MetadataButton.UseVisualStyleBackColor = false;
            //
            // ExitButton
            //
            resources.ApplyResources(this.ExitButton, "ExitButton");
            this.ExitButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(72)))), ((int)(((byte)(72)))));
            this.ExitButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.ExitButton.FlatAppearance.BorderColor = System.Drawing.Color.Gray;
            this.ExitButton.ForeColor = System.Drawing.Color.White;
            this.ExitButton.Name = "ExitButton";
            this.ExitButton.UseVisualStyleBackColor = false;
            //
            // SplitButton
            //
            resources.ApplyResources(this.SplitButton, "SplitButton");
            this.SplitButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(49)))), ((int)(((byte)(146)))));
            this.SplitButton.DataBindings.Add(new System.Windows.Forms.Binding("Enabled", this.MainBindingSource, "Invokable", true));
            this.SplitButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(39)))), ((int)(((byte)(128)))));
            this.SplitButton.ForeColor = System.Drawing.Color.White;
            this.SplitButton.Name = "SplitButton";
            this.SplitButton.UseVisualStyleBackColor = false;
            //
            // MainBindingSource
            //
            this.MainBindingSource.DataSource = typeof(Cube.Pdf.Pages.MainViewModel);
            //
            // MergeButton
            //
            resources.ApplyResources(this.MergeButton, "MergeButton");
            this.MergeButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(39)))), ((int)(((byte)(45)))));
            this.MergeButton.DataBindings.Add(new System.Windows.Forms.Binding("Enabled", this.MainBindingSource, "Invokable", true));
            this.MergeButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(37)))), ((int)(((byte)(43)))));
            this.MergeButton.ForeColor = System.Drawing.Color.White;
            this.MergeButton.Name = "MergeButton";
            this.MergeButton.UseVisualStyleBackColor = false;
            //
            // MainWindow
            //
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.CancelButton = this.ExitButton;
            this.Controls.Add(this.RootPanel);
            this.KeyPreview = true;
            this.Name = "MainWindow";
            this.RootPanel.ResumeLayout(false);
            this.FilePanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.FileListView)).EndInit();
            this.RightPanel.ResumeLayout(false);
            this.HeaderPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.TitleButton)).EndInit();
            this.FooterPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.MainBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel RootPanel;
        private System.Windows.Forms.TableLayoutPanel FilePanel;
        private System.Windows.Forms.Panel HeaderPanel;
        private System.Windows.Forms.PictureBox TitleButton;
        private FileListControl FileListView;
        private System.Windows.Forms.BindingSource MainBindingSource;
        private System.Windows.Forms.TableLayoutPanel FooterPanel;
        private Forms.Controls.Button ExitButton;
        private Forms.Controls.Button SplitButton;
        private Forms.Controls.Button MergeButton;
        private System.Windows.Forms.TableLayoutPanel RightPanel;
        private Forms.Controls.Button AddButton;
        private Forms.Controls.Button UpButton;
        private Forms.Controls.Button DownButton;
        private Forms.Controls.Button RemoveButton;
        private Forms.Controls.Button ClearButton;
        private Forms.Controls.Button MetadataButton;
    }
}

