//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Pdf.Clip.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Pdf.Clip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnLength {
            get {
                return ResourceManager.GetString("ColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添付状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPdf {
            get {
                return ResourceManager.GetString("FilterPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HeaderImage {
            get {
                object obj = ResourceManager.GetObject("HeaderImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   パスワードで保護された PDF ファイルの編集には未対応です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageEncryption {
            get {
                return ResourceManager.GetString("MessageEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} は他のプロセスによって開かれているため、操作を完了できません。ファイルを閉じてから再試行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLock {
            get {
                return ResourceManager.GetString("MessageLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの添付が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添付済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusEmbedded {
            get {
                return ResourceManager.GetString("StatusEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusNew {
            get {
                return ResourceManager.GetString("StatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubePDF Clip について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添付するファイルを選択して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleAttach {
            get {
                return ResourceManager.GetString("TitleAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添付対象となる PDF ファイルを選択して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleOpen {
            get {
                return ResourceManager.GetString("TitleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.cube-soft.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionWeb {
            get {
                return ResourceManager.GetString("VersionWeb", resourceCulture);
            }
        }
    }
}
